# Generated by Django 5.0.14 on 2026-01-05 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('notification_type', models.CharField(choices=[('new_request', 'New Request'), ('request_accepted', 'Request Accepted'), ('helper_en_route', 'Helper En Route'), ('helper_arrived', 'Helper Arrived'), ('service_completed', 'Service Completed'), ('request_cancelled', 'Request Cancelled'), ('new_message', 'New Message'), ('payment_received', 'Payment Received'), ('rating_received', 'Rating Received'), ('system', 'System Notification')], default='system', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField(help_text='Rating from 1-5')),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
