# Generated by Django 5.0.14 on 2026-01-05 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(blank=True, help_text='Professional license or ID number', max_length=50, null=True, unique=True)),
                ('bio', models.TextField(blank=True, help_text='Short bio or description of services')),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=False, help_text='Whether helper is currently available for jobs')),
                ('is_online', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('service_radius_km', models.FloatField(default=10.0, help_text='Maximum distance (km) helper will travel')),
                ('rating_avg', models.FloatField(default=0.0)),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('id_document', models.ImageField(blank=True, help_text='Government-issued ID for verification', null=True, upload_to='helper_documents/id/')),
                ('license_document', models.ImageField(blank=True, help_text='Professional license/certification document', null=True, upload_to='helper_documents/license/')),
            ],
            options={
                'verbose_name': 'helper',
                'verbose_name_plural': 'helpers',
                'ordering': ['-rating_avg', '-total_jobs'],
            },
        ),
        migrations.CreateModel(
            name='HelperSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('estimated_duration_minutes', models.IntegerField(default=30, help_text='Estimated duration to complete this service')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(help_text='Icon name or emoji', max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base service price for this vehicle type', max_digits=10)),
                ('price_multiplier', models.FloatField(default=1.0, help_text='Price multiplier for this vehicle type')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
