# Generated by Django 5.0.14 on 2026-01-05 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helpers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='helper_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helperschedule',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='helpers.helper'),
        ),
        migrations.AddField(
            model_name='helper',
            name='service_types',
            field=models.ManyToManyField(blank=True, help_text='Services this helper can provide', related_name='helpers', to='helpers.servicetype'),
        ),
        migrations.AddField(
            model_name='helper',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, help_text='Vehicle types this helper can service', related_name='helpers', to='helpers.vehicletype'),
        ),
        migrations.AlterUniqueTogether(
            name='helperschedule',
            unique_together={('helper', 'day_of_week', 'start_time')},
        ),
    ]
