# Generated by Django 5.0.14 on 2026-01-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_urdu', models.CharField(blank=True, help_text='Name in Urdu', max_length=100)),
                ('code', models.CharField(help_text="Unique code like 'LHR', 'PKN'", max_length=20, unique=True)),
                ('latitude', models.FloatField(blank=True, help_text='Center latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Center longitude', null=True)),
                ('radius_km', models.FloatField(default=50, help_text='Coverage radius in km')),
                ('is_nationwide', models.BooleanField(default=False, help_text="True for 'All Pakistan' option")),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in dropdown list')),
            ],
            options={
                'verbose_name': 'service location',
                'verbose_name_plural': 'service locations',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
