# Generated by Django 4.2.27 on 2026-02-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpers', '0003_servicelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='is_available',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether helper is currently available for jobs'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='rating_avg',
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
