# Generated by Django 5.0.14 on 2026-01-05 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='request_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching for Helper'), ('matched', 'Helper Matched'), ('accepted', 'Accepted by Helper'), ('en_route', 'Helper En Route'), ('arrived', 'Helper Arrived'), ('in_progress', 'Service In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Request status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_description', models.TextField(help_text='Description of the problem')),
                ('urgency', models.CharField(choices=[('low', 'Low - Can Wait'), ('medium', 'Medium - Needs Help Soon'), ('high', 'High - Urgent'), ('emergency', 'Emergency - Safety Risk')], default='medium', max_length=20)),
                ('user_latitude', models.FloatField()),
                ('user_longitude', models.FloatField()),
                ('user_address', models.CharField(blank=True, max_length=500)),
                ('helper_latitude', models.FloatField(blank=True, null=True)),
                ('helper_longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching for Helper'), ('matched', 'Helper Matched'), ('accepted', 'Accepted by Helper'), ('en_route', 'Helper En Route'), ('arrived', 'Helper Arrived'), ('in_progress', 'Service In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_barter', models.BooleanField(default=False)),
                ('barter_terms', models.TextField(blank=True)),
                ('issue_images', models.JSONField(blank=True, default=list, help_text='List of image URLs showing the issue')),
                ('cancellation_reason', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'service request',
                'verbose_name_plural': 'service requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
