# Generated by Django 4.2.27 on 2026-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching for Helper'), ('matched', 'Helper Matched'), ('accepted', 'Accepted by Helper'), ('en_route', 'Helper En Route'), ('arrived', 'Helper Arrived'), ('in_progress', 'Service In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['created_at'], name='requests_se_created_ee7209_idx'),
        ),
    ]
